# Generated by Django 5.2.7 on 2026-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='events/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True),
        ),
    ]
