# Generated by Django 5.2.7 on 2026-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_image_url_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ImageField(upload_to='partners/vinogradova/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото партнера',
                'verbose_name_plural': 'Фото партнеров',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
