# Generated by Django 5.2.7 on 2026-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partnerphoto_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='partnerphoto',
            options={'verbose_name': 'Фото партнера', 'verbose_name_plural': 'Галерея партнеров'},
        ),
        migrations.AddField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('vinogradova', 'Ирина Виноградова'), ('IET', 'Институт экономики и туризма'), ('BPS', 'Отря имени Андрея Дубенского')], default='vinogradova', max_length=50, verbose_name='К какому партнеру относится?'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='image',
            field=models.ImageField(upload_to='partners/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись (необязательно)'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
