# Generated by Django 5.2.7 on 2026-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_options_alter_partnerphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('NarodnFront', 'Алексей Макеев'), ('RGO', 'Молодёжный клуб РГО «Владимир»'), ('BPS', 'БПС г.Владимир. Отряд имени Андрея Дубенского'), ('Veles', 'Велес'), ('IET', 'ИЭТ'), ('ARH', 'ИАСЭ'), ('vinogradova', 'Ирина Виноградова'), ('RPC', 'РПЦ')], default='vinogradova', max_length=50, verbose_name='К какому партнеру относится?'),
        ),
    ]
