# Generated by Django 5.2.7 on 2026-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_partnerphoto_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerphoto',
            name='video_url',
            field=models.URLField(blank=True, help_text='Вставьте полную ссылку на видео', null=True, verbose_name='Ссылка на видео (YouTube/VK)'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('NarodnFront', 'Алексей Мокеев'), ('RGO', 'Молодёжный клуб РГО «Владимир»'), ('BPS', 'БПС г.Владимир. Отряд имени Андрея Дубенского'), ('Veles', 'Велес'), ('IET', 'ИЭТ'), ('ARH', 'ИАСЭ'), ('vinogradova', 'Ирина Виноградова'), ('RPC', 'РПЦ')], default='vinogradova', max_length=50),
        ),
    ]
