# Generated by Django 5.2.7 on 2026-03-31 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partnerphoto_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerphoto',
            options={'verbose_name': 'Медиа партнера', 'verbose_name_plural': 'Медиа партнеров'},
        ),
        migrations.RemoveField(
            model_name='partnerphoto',
            name='video_url',
        ),
        migrations.AddField(
            model_name='partnerphoto',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='partners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])], verbose_name='Видео файл (MP4/MOV)'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='image',
            field=models.ImageField(upload_to='partners/photos/', verbose_name='Фото (или превью для видео)'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('NarodnFront', 'Алексей Макеев'), ('RGO', 'Молодёжный клуб РГО «Владимир»'), ('BPS', 'БПС г.Владимир. Отряд имени Андрея Дубенского'), ('Veles', 'Велес'), ('IET', 'ИЭТ'), ('ARH', 'ИАСЭ'), ('vinogradova', 'Ирина Виноградова'), ('RPC', 'РПЦ')], default='vinogradova', max_length=50, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
