# Generated by Django 5.2.7 on 2026-03-31 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_partnerphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerphoto',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Медиа партнера', 'verbose_name_plural': 'Медиа партнеров'},
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='video_file',
            field=models.FileField(blank=True, help_text='Оставьте пустым, если хотите добавить только фото', null=True, upload_to='partners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])], verbose_name='Видео файл (MP4/MOV)'),
        ),
    ]
