# Generated by Django 5.2.7 on 2026-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_partnerphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerphoto',
            name='partner_description',
            field=models.TextField(blank=True, help_text='Достаточно заполнить только у ОДНОЙ (любой) фотографии партнера, чтобы текст появился в заголовке раздела.', verbose_name='Описание партнера (рассказ)'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('NarodnFront', 'Алексей Мокеев'), ('RGO', 'Молодёжный клуб РГО «Владимир»'), ('BPS', 'БПС г.Владимир. Отряд имени Андрея Дубенского'), ('Veles', 'Велес'), ('IET', 'ИЭТ'), ('ARH', 'ИАСЭ'), ('vinogradova', 'Ирина Виноградова'), ('RPC', 'РПЦ')], default='vinogradova', max_length=50, verbose_name='Партнер'),
        ),
    ]
