# Generated by Django 5.2.7 on 2026-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partnerphoto_partner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_description',
            field=models.TextField(blank=True, help_text='Достаточно заполнить только у ОДНОЙ фотографии партнера, чтобы текст появился в заголовке раздела.', verbose_name='Описание партнера'),
        ),
        migrations.AlterField(
            model_name='partnerphoto',
            name='partner_slug',
            field=models.CharField(choices=[('NarodnFront', 'Алексей Мокеев'), ('RGO', 'Молодёжный клуб РГО «Владимир»'), ('BPS', 'БПС г.Владимир. Отряд имени Андрея Дубенского'), ('Veles', 'Велотур клуб "ВЕЛЕС"'), ('IET', 'Институт экономики и туризма'), ('ARH', 'Институт архитектуры, строительства и энергетики'), ('School', 'МБОУ СОШ №19'), ('vinogradova', 'Ирина Виноградова')], default='vinogradova', max_length=50, verbose_name='Партнер'),
        ),
    ]
